basePath: /api/v1
definitions:
  dto.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.LoginRes:
    properties:
      token:
        type: string
    type: object
  dto.RegisterReq:
    properties:
      age:
        type: integer
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.SocialMediaCreateReq:
    properties:
      name:
        type: string
      social_media_url:
        type: string
      user_id:
        type: integer
    type: object
  dto.SocialMediaListRes:
    properties:
      data:
        items:
          $ref: '#/definitions/entity.SocialMedia'
        type: array
      last_page:
        type: integer
      limit:
        type: integer
      page:
        type: integer
      total_data:
        type: integer
    type: object
  dto.SocialMediaUpdateReq:
    properties:
      name:
        type: string
      social_media_url:
        type: string
    type: object
  entity.SocialMedia:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      social_media_url:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/entity.User'
      user_id:
        type: integer
    type: object
  entity.User:
    properties:
      age:
        type: integer
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  helpers.ResponseDefault:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger MyGram API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: Login User
        in: body
        name: dto.LoginReq
        required: true
        schema:
          $ref: '#/definitions/dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginRes'
      summary: Login User
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register new User
      parameters:
      - description: Register User
        in: body
        name: dto.RegisterReq
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.User'
      summary: Register User
      tags:
      - Auth
  /social-media:
    get:
      consumes:
      - application/json
      description: Get All Social Media
      parameters:
      - description: Pagination Get All Social Media
        in: query
        name: page
        required: true
        type: integer
      - description: Pagination Get All Social Media
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SocialMediaListRes'
      summary: GetAll
      tags:
      - Social Media
    post:
      consumes:
      - application/json
      description: Create new data Social Media
      parameters:
      - description: Create SocialMedia
        in: body
        name: dto.SocialMediaCreateReq
        required: true
        schema:
          $ref: '#/definitions/dto.SocialMediaCreateReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.SocialMedia'
      summary: CreateSocialMedia
      tags:
      - Social Media
  /social-media/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Social Media by ID
      parameters:
      - description: Social Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.ResponseDefault'
      summary: DeleteSocialMedia
      tags:
      - Social Media
    get:
      consumes:
      - application/json
      description: GetOne Social Media by ID
      parameters:
      - description: Social Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SocialMedia'
      summary: GetOne
      tags:
      - Social Media
    put:
      consumes:
      - application/json
      description: Update Social Media by ID
      parameters:
      - description: Update SocialMedia
        in: body
        name: dto.SocialMediaUpdateReq
        required: true
        schema:
          $ref: '#/definitions/dto.SocialMediaUpdateReq'
      - description: Social Media ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SocialMedia'
      summary: UpdateSocialMedia
      tags:
      - Social Media
swagger: "2.0"
